add Network Client with API IMDb
grand-roman/MovieQuiz-ios pull request #5
Opened 2022-11-27 14:21 UTC by grand-roman

2022-11-28 09:08 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. С пустым списком приложение будет выглядеть сломанным. Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, эту ошибку лучше вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2022-11-28 09:22 UTC, ABashkirova requested changes
Привет! Обязательно поправь ошибку с определением вопроса квиза.
Остальное опционально

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
Рекомендую, использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у activityIndicator вместо ручного управления isHidden. Эту настройку можно сделать один раз во viewDidLoad или на сториборде.

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. С пустым списком приложение будет выглядеть сломанным. Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, эту ошибку лучше вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +      }
control+i на выделенном участке, чтобы исправить форматирование

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                    if mostPopularMovies.items.isEmpty{
```suggestion
                    if mostPopularMovies.items.isEmpty {
```

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/MoviesLoader.swift
> +                        handler(.failure(loadingMovieError.loadError))
👍🏻

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        moviesLoader?.loadMovies { result in
Здесь не критично и не приводит к ошибке, однако потенциальное проблемное место из-за пропущенного ослабления ссылки 
```suggestion
        moviesLoader?.loadMovies { [weak self] result in
```

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didFailToLoadImage()
обращу внимание, что метод requestNextQuestion не закончил работу и пойдет выполняться дальше, вызовет didReceiveNextQuestion без постера

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                    guard let self = self else { return }
👍🏻 

в новой версии свифта можно еще так 
```suggestion
                    guard let self else { return }
```

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private func generateTextAnswer(rating: Float) -> (text: String, correctAnswer: Bool){
перед фигурной скобкой не забывай ставить пробел :) 
```suggestion
    private func generateTextAnswer(rating: Float) -> (text: String, correctAnswer: Bool) {
```

2022-11-28 09:22 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        if let word = ["больше", "меньше"].randomElement() {
Наверное имелось ввиду, потому что иначе дальнейшее сравнение на correctAnswer может содержать ошибку, так как word в первом случае и во втором - могут отличаться)
```suggestion
        if let word = word {
```

2022-11-29 06:54 UTC, grand-roman commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Мне бы пример такого случая 
Чтобы увидеть ошибку на сервисе и понимать как ее обрабатывать правильно и где

2022-11-29 07:46 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Окей, я выше написала примеры. Из них самый простой для проверки: `API key неверный` – просто поменяй ключ на набор символов и запусти.

2022-11-29 10:35 UTC, grand-roman commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
А понял щас

2022-11-29 13:36 UTC, grand-roman commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
А разве в этом моменты мы не проверяем что список пустой ?

2022-11-29 14:59 UTC, ABashkirova approved these changes
Можно смерджить (после правок)

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
> А разве в этом моменты мы не проверяем что список пустой ?

Роман, ты прав. Фактически в данном случае хватает проверки на пустой/не пустой список. Этого достаточно и можно удалить errorMessage, ведь он не задействован ни в проверке, ни для вывода конкретного сообщения. 

Но тут какая штука получается: 
- во первых текст ошибки от сервера конкретный, то есть можно прям пользователю это показать (обыграв конечно на понятные текста)
- во вторых, как я уже писала, что это ошибка проектирования сервиса IMDB, которая **может**(необязательно что будет) давать _вырожденные_ случаи:
  - список пустой, ошибки нет (пустая строка) — вырожденный случай
  - список пустой, ошибка есть — так действительно работает сервис, сценарий с ошибкой
  - список не пуст, ошибки нет — так действительно работает сервис, сценарий с позитивным ответом 
  - список не пуст, ошибка есть – еще один вырожденный случай. 

Структура дает все четыре возможных варианта, и по-хорошему на клиете иметь от них обработку, ведь серверный разработчик (бекендер) может случайно ошибиться и начать присылать ответы по вырожденным сценариям.

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.noButton.tintColor = UIColor.ypBlack
Если возможно — стоит опускать self
```suggestion
        yesButton.isEnabled = true
        noButton.isEnabled = true
        yesButton.tintColor = UIColor.ypBlack
        noButton.tintColor = UIColor.ypBlack
```

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.activityIndicator.hidesWhenStopped = true
```suggestion
        activityIndicator.hidesWhenStopped = true
```

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            guard let self else {return}
```suggestion
            guard let self else { return }
```

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        if let word = word {
супер, а теперь можно использовать короткий синтаксис: 
```suggestion
        if let word {
```

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
Теперь можно удалить
```suggestion
```

2022-11-29 14:59 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.stopAnimating()
можно, чтобы было симметрично, написать функцию hideLoadingIndicator

2022-11-30 07:30 UTC, merged